# Generated by Django 2.2.19 on 2024-04-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20240416_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupoint',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка'),
        ),
    ]
