# Generated by Django 2.2.19 on 2024-04-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20240416_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='position',
        ),
    ]
