# Generated by Django 2.2.19 on 2024-04-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menu_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('id',), 'verbose_name': 'suka', 'verbose_name_plural': 'suka'},
        ),
        migrations.AlterModelOptions(
            name='menupoint',
            options={'ordering': ('id',), 'verbose_name': 'Подпункты', 'verbose_name_plural': 'Подпункты'},
        ),
    ]
