# Generated by Django 2.2.19 on 2024-04-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20240418_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupoint',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.MenuPoint'),
        ),
    ]
